"""add dailydata

Revision ID: 002dc67ed0f5
Revises: 0a85ef034c7e
Create Date: 2025-06-25 19:49:21.277218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '002dc67ed0f5'
down_revision = '0a85ef034c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('food_type', sa.String(length=100), nullable=True),
    sa.Column('meals_number', sa.Integer(), nullable=True),
    sa.Column('water_intake', sa.Boolean(), nullable=True),
    sa.Column('water_amount', sa.Float(), nullable=True),
    sa.Column('exercised', sa.Boolean(), nullable=True),
    sa.Column('activity_type', sa.String(length=100), nullable=True),
    sa.Column('exercise_duration', sa.Integer(), nullable=True),
    sa.Column('poop_quality', sa.String(length=20), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('appetite', sa.String(length=20), nullable=True),
    sa.Column('energy_level', sa.String(length=20), nullable=True),
    sa.Column('mood', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_data')
    # ### end Alembic commands ###
