"""add medical record

Revision ID: 0a85ef034c7e
Revises: e567dd5e3232
Create Date: 2025-06-25 19:39:07.255526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '0a85ef034c7e'
down_revision = 'e567dd5e3232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.Enum('vaccination', 'medication', 'surgery', 'checkup', 'lab', 'other', name='recordtypeenum'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('horse_market_listings',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('horse_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('is_active', mssql.BIT(), server_default=sa.text('((1))'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], name=op.f('FK__horse_mar__horse__71D1E811')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__horse_ma__3213E83F6A773812'))
    )
    op.drop_table('medical_records')
    # ### end Alembic commands ###
