"""add HorseImage table"

Revision ID: 31a31f3b8b6d
Revises: 
Create Date: 2025-06-22 17:32:31.586005
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a31f3b8b6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horse_images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('horse_id', sa.Integer(), nullable=False),
        sa.Column('image_url', sa.String(length=255), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # حذفت تعديل users.email
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('horse_images')
    # حذفت تعديل users.email
    # ### end Alembic commands ###
