"""add imgae url to posts

Revision ID: 49f0cd863a75
Revises: a25a81cd2eea
Create Date: 2025-07-12 19:54:49.560046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '49f0cd863a75'
down_revision = 'a25a81cd2eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
