"""add image url

Revision ID: a25a81cd2eea
Revises: c97ded5c6383
Create Date: 2025-07-10 18:15:22.564966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'a25a81cd2eea'
down_revision = 'c97ded5c6383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horse_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('horse_listings', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
