"""add image url

Revision ID: c97ded5c6383
Revises: 0a029018705e
Create Date: 2025-07-08 16:17:52.102522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'c97ded5c6383'
down_revision = '0a029018705e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    
    # ### end Alembic commands ###
