"""ocr update

Revision ID: f6fbc4610426
Revises: 49f0cd863a75
Create Date: 2025-07-12 21:35:51.353755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'f6fbc4610426'
down_revision = '49f0cd863a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sire', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('dam', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('blood_type', sa.String(length=50), nullable=True))
        batch_op.drop_column('breed')
        batch_op.drop_column('country_of_birth')
        batch_op.drop_column('breeder')
        batch_op.drop_column('price')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    with op.batch_alter_table('horses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('breeder', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country_of_birth', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('breed', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.drop_column('blood_type')
        batch_op.drop_column('dam')
        batch_op.drop_column('sire')

    # ### end Alembic commands ###
