"""added some shit

Revision ID: ffad1fbb1a66
Revises: f6fbc4610426
Create Date: 2025-07-13 04:33:14.273768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'ffad1fbb1a66'
down_revision = 'f6fbc4610426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_tree', schema=None) as batch_op:
        batch_op.alter_column('is_root',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('family_tree', schema=None) as batch_op:
        batch_op.alter_column('is_root',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))

    # ### end Alembic commands ###
